gText_Birch_Welcome:: @ 82C897B
	.string "Ello!\p"
	.string "Welcome to the world of Cranbrook!\p"
	.string "My name is Dr. Reynolds.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “POKéMON.”\p"
	.string "But you already know that.\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Here at CRANBROOK we use POKéMON,\n"
	.string "as our slaves. Holding them captive, and\l"
	.string "making them bend over to our\l"
	.string "every whim and desire\p"
	.string "And sometimes, we like to make them\n"
	.string "battle each other for fun.\p"
	.string "Despite my expertise, I don't\n"
	.string "own every POKéMON.\p"
	.string "In fact, I've been undertaking research,\n"
	.string "to try and capture them all and,\l"
	.string "rule CRANBROOK with an iron fist.\n"
	.string "Anyway, that's enough about me.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "You are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} the new student\n"
	.string "in my lab!\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Wait! What did you just say?\p"
	.string "You are going to try and\n"
	.string "stop me?\p"
	.string "Silly child you don't have\n"
	.string "the brains or brawn to keep me\l"
	.string "from my goal of being\l"
	.string "the supreme ruler of this school!\p"
	.string "If you dare to defy me.\n"
	.string "Meet me at my POKéMON LAB.\p"
	.string "$"
